### ISSUE TITLE
Fake git environment for testing

### ISSUE THREAD

**Issue by maresb** [pyscaffold/pyscaffoldext-markdown#11]
Tests for both `pyscaffoldext-markdown` and `pyscaffoldext-dsproject` rely on `git` being configured, i.e. the username and e-mail to be set. If not, PyScaffold raises [`GitNotConfigured`](https://github.com/pyscaffold/pyscaffold/blob/6ff81035de3da737af8fe90841b7ba4b56dcc5a2/src/pyscaffold/info.py#L127).

In contrast, PyScaffold is able to perform tests even when `git` is unconfigured. This seems to come from [this fake git config mechanism](https://github.com/pyscaffold/pyscaffold/blob/61cc6964cc05593885e65184c65b58a5a4676f6c/tests/conftest.py#L31-L76).

I'm actually curious what the best practices for this should be. It seems to me like one should import the fixtures from PyScaffold for use in extension testing. But the fixtures are part of `tests/`, not part of `src/`, so one can't simply import them. (I really love how PyScaffold makes `src/` explicit, despite all the complications which follow.) But it's also an antipattern to copy the code.

Reading through the pytest docs, it looks like the recommended solution is to use [pytest_plugins](https://docs.pytest.org/en/stable/fixture.html#using-fixtures-from-other-projects).

This all seems like a lot of work, and I'm not convinced that it's worthwhile, but I wanted to put the idea out.

Regarding the specific case of the conda-forge CI, I did manage to find a quick non-windows workaround [by setting environment variables](https://github.com/conda-forge/staged-recipes/commit/f3c5e9f). There is however a peculiarity in the way conda-forge feedstocks are tested...

During staging, the recipes are tested on win/osx/linux. After they are accepted and converted into feedstocks, if they are noarch feedstocks, then they are only tested against linux. Thus I could now go in and revert to the indicated commit, and all the checks should pass. This however feels a bit like cheating to me.

**Comment by abravalheri** [comment]
Hi @maresb, I will add some quick comments here, but later I will have to revisit this issue and check properly the references you provided.

There are some tests in out test suite that would break if the developer running them on their machine have a PyScaffold [default configuration file](https://pyscaffold.org/en/stable/configuration.html#pyscaffold-s-own-configuration) (as introduced in v4). One solution would be specifying `--no-config` every time we run PyScaffold on the tests... However as you might imagine, migrating the test code base from v3 to v4 would be a massive task, because we have a very big test code base. So I opted for faking the entire home folder instead. Not sure how controversial that might be considered, but it definitely improves the test isolation...

For the new code bases depending on PyScaffold, what I have been doing is explicitly specifying ``--no-config`` (as shown in [pyscaffoldext-markdown](https://github.com/pyscaffold/pyscaffoldext-markdown/blob/f3c0e033bf076fd9219874f6ee564728fabc6e8a/tests/test_custom_extension.py#L19))

**Comment by abravalheri** [comment]
I don't think there would be a problem in using env vars for configuring git, as long as it does not complain on not having a `.gitconfig` file available...

The problem in the approach for the yaml file, is that the syntax is Linux specific... ideally we need to be able to specify the env vars in a non OS-dependant way inside the recipe file... Unfortunately by quickly scanning the [reference](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html), I could not find it.

**Comment by abravalheri** [comment]
Sorry if I digressed 😝, I was just trying to justify that `fake_home` (and therefore `_config_git`) where never meant to solve this particular problem, and that configure git beforehand (or using the env vars) are still the recommended approach. I don't know if it is worthy the trouble of creating (and publishing) pytest plugins...

I have to give it a thought... I suppose the "conda-way" would be specifying separated scripts... `run_test.sh` --- or `.bat`, `.py`, or `.pl`

[LATE EDIT]
I just noticed this PR https://github.com/conda/conda-build/pull/3889 merged into conda. I don't know if this syntax is only available for the `build` section, or also for `test`, but that would be a nice solution wouldn't it?

**Comment by maresb** [comment]
Hmm, regarding the environment varialbes, in conda-forge we don't invoke conda-build explicitly. Everything is driven by the `meta.yaml` file. Thus I don't think that would help us in this case.

Ah, but you very cleverly point out the use of `run_test.[sh,bat,py,pl]`. I had overlooked that before. (There are several restrictions for noarch packages, and I'm not sure whether or not such a script is allowed, but at first glance I see no indication against.)

I agree that it would be a lot of work to publish pytest plugins. I honestly don't really see any todos here which I'd consider worth the effort from my side, at least with any of my current ideas.

**Comment by maresb** [comment]
Feel free to close this with wont-fix or whatever. :)

**Comment by abravalheri** [comment]
I think this could be turned into a discussion in PyScaffold.
