### ISSUE TITLE
Switch to MyST-Parser from recommonmark (no longer maintained) 

### ISSUE THREAD

**Issue by DrShushen** [pyscaffold/pyscaffoldext-markdown#14]
## Description of use-case
`pyscaffoldext-markdown` currently sets up `recommonmark` as the extension for Sphinx markdown support. However, navigating to [recommonmark docs](https://recommonmark.readthedocs.io/en/latest/) one is greeted with a "No Maintenance Intended" banner, as this extension is now being sunset.

## Description of solution
As described in this [issue](https://github.com/readthedocs/recommonmark/issues/221) on `recommonmark` GitHub, it is being sunset in favour of [MyST-Parser](https://github.com/executablebooks/MyST-Parser/). `pyscaffoldext-markdown` should be updated to set things up for MyST-Parser instead.

**Comment by FlorianWilhelm** [comment]
Thanks, @DrShushen for letting us know. Would you like to help us out with a PR?

**Comment by DrShushen** [comment]
@FlorianWilhelm I've just been testing out MyST integration on my PyScaffold templated project. Will have a look at contribution guidelines and try to submit a PR for this in the next week or so.

**Comment by abravalheri** [comment]
I am impressed that they are recommending MyST now, `recommonmark` was a much more conservative project, MyST does some wild cool things...

Since MyST have a much more feature-full parser, I consider this change to be a good thing for the project and for the users. For example, MyST can do Markdown imports, and therefore we don't have to rely on the symbolic link trick to include the changelogs, readme, etc (which requires some effort to work on windows)...

I wonder if there is anyway to configure sphinx+MyST to export latex (even if indirectly)... For what I see, MyST have most of the things you need to even publish scientific papers...

**Comment by DrShushen** [comment]
@FlorianWilhelm PR #16 submitted for this.
